.TH dvgrabgui-wx-2.8 1 "april 10, 2008"

.SH NAME
dvgrabgui \- a graphical program to capture dv stream from a camera
(wxWidgets 2.8 version).

.SH SYNOPSIS
.B dvgrabgui

.SH DESCRIPTION
This manual page documents briefly the
.B dvgrabgui
commands.

.PP
\fBdvgrabgui\fP is a program that shows frames from a dv camera, and capture the
dv stream. See the help included in the interface.

.SH OPTIONS
No options on command line!

.SH SEE ALSO
The program is documented fully by the help available from its interface,
or the html files in \fB/usr/share/doc/dvgrabgui/help/<lang>/main.html\fB.

.SH AUTHOR
dvgrabgui was written by Bastien Montagne <montagne29@wanadoo.fr>.

.PP
This manual page was written by Bastien Montagne <montagne29@wanadoo.fr>,
for the Debian project (but may be used by others).
