.TH dvgrabgui-wx-2.8 1 "april 10, 2008"

.SH NAME
dvgrabgui \- Un programme graphique pour capturer un flux dv depuis une caméra
(version avec wxWidgets 2.8).

.SH SYNOPSIS
.B dvgrabgui

.SH DESCRIPTION
Cette page de manuel décrit brièvement la commande 
.B dvgrabgui.

.PP
\fBdvgrabgui\fP est un programme qui montre les images provenant d'une caméra
dv, et enregistre le flux dv. Voyez l'aide incluse dans l'interface graphique.

.SH OPTIONS
Pas d'option pour la ligne de commande!

.SH SEE ALSO
Ce programme est complètement documenté par l'aide accessible depuis son
interface, ou les fichiers html dans
\fB/usr/share/doc/dvgrabgui/help/<lang>/main.html\fB.

.SH AUTHOR
dvgrabgui a été écrit par Bastien Montagne <montagne29@wanadoo.fr>.

.PP
Cette page de manuel a été écrite par Bastien Montagne <montagne29@wanadoo.fr>,
pour le projet Debian (mais peut être utilisée par d'autres).
