.TH dvgrabgui-wx-2.8 1 "april 10, 2008"

.SH NAME
dvgrabgui \- un programa gráfico para capturar un flujo dv desde una cámara
(versión con wxWidgets 2.8).

.SH SYNOPSIS
.B dvgrabgui

.SH DESCRIPTION
Esta página describe brevemente los mandos de 
.B dvgrabgui.

.PP
\fBdvgrabgui\fP es un programa que muestra imágenes desde una cámara dv, y graba
el flujo dv. Vea la ayuda dentro de la interfaz gráfica.

.SH OPTIONS
¡No opción en la línea de mando!

.SH SEE ALSO
El programa está documentado completamente por la ayuda accesible desde su
interfaz gráfica, o los ficheros html en
\fB/usr/share/doc/dvgrabgui/help/<lang>/main.html\fB.

.SH AUTHOR
dvgrabgui ha sido escrito por Bastien Montagne <montagne29@wanadoo.fr>.

.PP
Esta página de manual ha sido escrita por Bastien Montagne
<montagne29@wanadoo.fr>, para el proyecto Debian (pero puede ser utilizada por
otros).
